# 切换配置文件
spring:
  profiles:
    active: devp
---
server:
  port: 8888

database: redis

# 对象
person:
  name: laughing

# 数组
language:
  - java
  - go

# 单引号不会识别转义字符，双引号可以识别转义字符
go: 'fmt.Println()'
java: "System.out.println()"

spring:
  profiles: devp
---
server:
  port: 8899

database: redis

# 对象
person:
  name: laughing

# 数组
language:
  - java
  - go

go: 'fmt.Println()'
java: "System.out.println()"

spring:
  profiles: tests
---